### ISSUE TITLE
What's the rationale of having IDs shorter than 15 bits?

### ISSUE THREAD

**Issue by BioFalcon** [oushujun/LTR_retriever#113]
Hi, 

I was just wondering why is the need of having IDs shorter than 15 bits? I couldn't find the reason in the doc.

Cheers
F

**Comment by oushujun** [comment]
Hi @BioFalcon,

The limitation is originated from RepeatMasker since LTR_retriever uses it to process candidates. RepeatMasker has 50 characters ID space, but since LTR_retriever uses coordinates as sequence IDs, and assuming the longest chromosome of 999 Mb, the longest ID looks like: Chr:xxxxxxxxx..xxxxxxxxx#LTR/unknown. This leaves ~15 characters for the Chr.

They do have a plan to improve this: https://github.com/rmhubley/RepeatMasker/issues/12

Shujun
