### ISSUE TITLE
LAI for Big Genome

### ISSUE THREAD

**Issue by pxxiao-hz** [oushujun/LTR_retriever#129]
Hi, @oushujun 

For big genomes, can I split genome to run this pipeline to get the LAI? In this way, it's faster than the whole genome.

Best wishes!

**Comment by oushujun** [comment]
You may split the genome to get the full list of intact LTR and all LTR
faster. It's recommended to run LAI on the full ploidy, otherwise it could
not represent the genome. You need to split a polyploid genome based on
subgenomes or haplotype to run LAI, otherwise it will underestimate the
score.

Shujun
