### ISSUE TITLE
No tbl file

### ISSUE THREAD

**Issue by aisangekoukou** [oushujun/LTR_retriever#134]
Hello Shujun Ou:

When I run the LTR_retriever, It happened errors as follows:

14:37:21 CST	Start to annotate whole-genome LTR-RTs...
				Use -noanno if you don't want whole-genome LTR-RT annotation.

grep: genome.fa.tbl: No such file or directory
famcoverage.pl TE_lib RM_output genome_size_bp > TE_fam.size.list

fam_summary.pl TE_fam.size.list genome_size_bp > TE_fam.sum.txt

perl LTR_sum.pl -genome genome.fa -all genome.fa.RM.out [options]
	-window [int]	bp size of the sliding window, default 3,000,000
	-step [int]	bp size of the moving step, defalut 300,000
	-intact		indicate the -all file is an LTR_retriever .pass.list instead of a RepeatMasker .out file
sort: cannot read: genome.fa.out: No such file or directory
Input file(s) not exist!

The following is my commands:

nohup LTR_retriever -threads 20 -u 7e-9 -genome genome.fa -inharvest genome.fa.LTRharvest.scn -infinder genome.fa.finder.combine.scn > LTR_retriever.log 2>&1 &

Could you give some suggestions?

Thanks

**Comment by oushujun** [comment]
Hello @aisangekoukou,

Sorry for the delayed response. I can't see any issues here. Have you tried with other genomes or a test data like Arabidopsis?

Thanks,
Shujun

**Comment by aisangekoukou** [comment]
Thanks for your reply. I have already fixed the error with Arabidopsis. I guess it may be because there is only one chromosome in my test data. Thank you for your attention.

**Comment by yangruixue-xue** [comment]
> Thanks for your reply. I have already fixed the error with Arabidopsis. I guess it may be because there is only one chromosome in my test data. Thank you for your attention.

Hi, how did you solve it? I had the same problem：
My command is：
LTR_retriever -genome Arabidopsis.fa -inharvest genome.farawLTR.scn -threads 10
mistake llie this ,
grep: OB_hap1.fa.tbl: No such file or directory
famcoverage.pl TE_lib RM_output genome_size_bp > TE_fam.size.list

fam_summary.pl TE_fam.size.list genome_size_bp > TE_fam.sum.txt

perl LTR_sum.pl -genome genome.fa -all genome.fa.RM.out [options]
-window [int] bp size of the sliding window, default 3,000,000
-step [int] bp size of the moving step, defalut 300,000
-intact indicate the -all file is an LTR_retriever .pass.list instead of a RepeatMasker .out file
sort: cannot read: OB_hap1.fa.out: No such file or directory
Input file(s) not exist!

The LTR Assembly Index (LAI) is developed to evaluate the assembly continunity of repetitive sequences

Usage: ./LAI -genome genome.fa -intact intact.pass.list -all genome.out [options]
Options:
-genome [file] The genome file that is used to generate everything.
-intact [file] A list of intact LTR-RTs generated by LTR_retriever (genome.fa.pass.list).
-all [file] RepeatMasker annotation of all LTR sequences in the genome (genome.fa.out).
-window [int] Window size
otate whole-genome LTR-RTs...
Use -noanno if you don't want whole-genome LTR-RT annotation.

Fri Jan 17 10:57:40 UTC 2025 All analyses were finished!

##############################
####### Result files #########
##############################

Table output for intact LTR-RTs (detailed info)
OB_hap1.fa.pass.list (All LTR-RTs)
OB_hap1.fa.nmtf.pass.list (Non-TGCA LTR-RTs)
OB_hap1.fa.pass.list.gff3 (GFF3 format for intact LTR-RTs)

LTR-RT library
OB_hap1.fa.LTRlib.redundant.fa (All LTR-RTs with redundancy)
OB_hap1.fa.LTRlib.fa (All non-redundant LTR-RTs)
OB_hap1.fa.nmtf.LTRlib.fa (Non-TGCA LTR-RTs)

Whole-genome LTR-RT annotation by the non-redundant library
OB_hap1.fa.LTR.gff3 (GFF3 format)
OB_hap1.fa.out.fam.size.list (LTR family summary)
OB_hap1.fa.out.superfam.size.list (LTR superfamily summary) @aijigekoukou-shen @oushujun
