### ISSUE TITLE
A question about LAI in autopolyploid

### ISSUE THREAD

**Issue by kedduck** [oushujun/LTR_retriever#145]
Dear oushujun

Thanks for your great software about LTR annotation and LAI calculation.

 I have browsed the previous issue about LAI in ploypolids species. In general, I may get the mean that the different subgenome should calculate separately.

 I have a simple question about LAI in autopolyploids species. There is an autopolyploids  reference genome with  4 haplotypes. I want to compare it with my  4 new haplotypes of the same species. Could I  use the whole genome to calculate LAI to compare？

If I want to compare  interspecies should I select 1 haplotpye randomly  in each chromosome?

Looking forward to your reply !

**Comment by oushujun** [comment]
Hello,

No you still can't use the whole autopolyploid genome to calculate LAI. Actually, it is the worse case to do so because autoployploids have highly identical sequences between subgenomes and will negatively impact the LAI adjustment.

You may select 1 haplotype randomly for each paralogs to represent thsi sepcies. Or randomly assign haplotypes into four subgenomes and calculate LAI for each of them, then make an average of subgenome LAIs to represent this species.

Best,
Shujun

**Comment by kedduck** [comment]
Thanks for your detailed reply!
