### ISSUE TITLE
Support for MGEScan

### ISSUE THREAD

**Issue by zengxiaofei** [oushujun/LTR_retriever#19]
Hi Dr. Ou,

According to the manual of LTR_retriever, the input from MGEScan was generated by "a modified version of DAWGPAWS" -- `find_ltr_DAWGPAWS.pl`. And `bin/run_MGEScan.pl` also calls for the script:
```Perl
my $DAWGPAWS_path="/mnt/home/oushujun/git_bin/MGEScan_LTR";
```
However, it seems that the script has not been provided in the LTR_retriever.

I have tried to use the original version of DAWGPAWS by myself, but it is quite hard to use.  I should be most grateful if you would send me the script (Email: xiaofei_zeng@whu.edu.cn).

Thank you very much
Xiaofei

**Comment by oushujun** [comment]
Dear Xiaofei,

Thank you for using LTR_retriever. The `MGEScan_LTR` was used in our paper for the purpose of benchmarking. As you experienced, it requires some modifications for further use. I didn't provide the modified code because it's not necessary to use `MGEScan_LTR` as I mentioned in #8 and in our paper. The inclusion of `MGEScan_LTR` only improve the sensitivity marginally and will also introduce false discovery. Thus it's not worth the trouble.

If you want to use it anyways, you can try to modify the output of `MGEScan_LTR` into the `LTRharvest` format, then feed the program by `-inharvest converted.scn`.

Thanks!

Shujun

**Comment by zengxiaofei** [comment]
Thank you very much!
