### ISSUE TITLE
LTRharvest as input

### ISSUE THREAD

**Issue by xinshuaiqi** [oushujun/LTR_retriever#22]
Hi Shujun, 
I notice the updated Readme file now suggest using "LTRharvest" as input file. 
Are there any reason LTR_finder no longer preferred?
Is the result based on solo LTRharvest robust enough?

**Comment by oushujun** [comment]
Hi Xinshuai,

The line you were suggesting in the `ReadMe` is just an example to run `LTR_retriever`. Please refer to the full usage in the manual pdf. It is still recommended to use both `LTRharvest` and `LTR_finder` as raw input to improve the LTR library sensitivity (marginally, though, please refer to the supplementary table for this margin) for the purpose of whole-genome LTR annotation. For the use of LAI, it is strongly recommended to use **both** inputs to fully identify intact LTR-RTs, otherwise the resulting LAI could drop a couple points.

Shujun
