### ISSUE TITLE
Zombie process is generated when run  LTR.identifier.pl

### ISSUE THREAD

**Issue by forrwill** [oushujun/LTR_retriever#50]
Hi Shujun,

       I found some  process  become zombie process when I had been run it a long time;
There are partly result of command top :

> `SN   Jul11   0:00      \_ sh -c perl /bin/LTR.identifier.pl final.fasta ...`
`Sl   Jul11 393:51          \_ perl /bin/LTR.identifier.pl final.fasta ...`
`Z    Jul12   0:00                  \_ [perl] <defunct>`
`Z    Jul12   0:01                   \_ [perl] <defunct>`
`Z    Jul12   0:01                   \_ [perl] <defunct>`
`Z    Jul12   0:01                    \_ [sh] <defunct>`
`Z     Jul12   0:01                   \_ [perl] <defunct>`
`Z    Jul12   0:01                    \_ [perl] <defunct>`
`Z    Jul12   0:01                    \_ [perl] <defunct>`

    
       I ran two different data, both of which will be stuck in these states(Z).
Can you give some advice to avoid such problems? should I use single thread? Thanks!

**Comment by oushujun** [comment]
Hello,

If you can see new data are generating to the .defalse file, then they are
probably fine. Otherwise you may have allocated more threads than your
system currently has and the multithreading module is stuck in this. For
this situation you need to cancel and rerun it with less threads, say, 10
works very well for me.

Shujun

**Comment by forrwill** [comment]
Hi Shujun,
Thanks a lot, .defalse file stopped updating, in the server used before, there are too many tasks competing for resources; I will try to reduce the thread and run on a server with sufficient resources
