### ISSUE TITLE
substr outside of string

### ISSUE THREAD

**Issue by sahammond** [oushujun/LTR_retriever#6]
Hi,
I've been having some trouble running LTR_retriever on my genome. I get the error noted below hundreds of thousands of times in my log, and no LTRs end up being identified.

>
Thu Jul 13 17:37:31 PDT 2017    Start to convert inputs...
substr outside of string at /projects/btl/shammond/git/LTR_retriever/bin/call_seq_by_list.pl line 120.
Use of uninitialized value $seq in string eq at /projects/btl/shammond/git/LTR_retriever/bin/call_seq_by_list.pl line 121.
>

I supplied predictions from LTRharvest, both TGCA and non-TGCA, and LTRfinder.

Also, I don't know if it's related to the above, but I see some unexpected sequences in my nmtf.ltrTE.fa file, such as blank or all-N sequences.

Could there be a problem with my input?

**Comment by oushujun** [comment]
Hi,

Seems like the problem was from the inputs. Could you double check the supplied genome? See if sequence names are in a simple format (short, un-spaced, no special characters) and if the genome is the same with the one you used to obtain LTR candidates (it happens when you have multiple assembly practices).

Another thing you can try is to supply input files separately. For example, just run with the TGCA input, then add non-TGCA, or run with the finder input, then add them all up. This will help to locate where the problem is.

If you could not find anything wrong, can you email me your prediction files?

Thanks!
Shujun

**Comment by sahammond** [comment]
Hi Shujun,

My LTR candidates were obtained from an older version of the genome. I'm running LTR_retriever now with the matched assembly and everything seems to be going fine.

Thanks!
Austin
