### ISSUE TITLE
Can LAI be a good metric for contiguous assemblies with a relatively high consensus error rate?

### ISSUE THREAD

**Issue by chocotwig** [oushujun/LTR_retriever#72]
Hi,
I have an assembly that happens is relatively contiguous, but generated using error-prone long read sequencing. Our assembly is unpolished, and has a consensus base-level error rate of about 5-7%. In your reckoning, could LAI still be a good metric for assessing this assembly? 

Thanks!

**Comment by oushujun** [comment]
No - LAI relies on accurate sequences because it needs to estimate the divergence of LTR sequences to account for LTR activities. If there are basepair differences between two LTR sequences, LAI can not distinguish whether the difference is due to mutation or sequencing error. And the later one will overcorrect LAI values (low LAI) because the program thought LTRs are old.

Shujun
