### ISSUE TITLE
Calculate LTR insertion time using all LTR rather than only intact LTR

### ISSUE THREAD

**Issue by xiaoyezao** [oushujun/LTR_retriever#79]
Hi,

 I am wondering is it ok to calculate LTR insertion time using the "`identity`" from the result file `genome.mod.retriever.all.scn` ?

Bests,
Tao

**Comment by oushujun** [comment]
Hi Tao,

Entries in the genome.mod.retriever.all.scn file are not the result of
LTR_retriever. The file contains all possible candidates from the input so
some of them are false positives. Only entries in the pass.list file are
considered real LTR retrotransposons.

Best,
Shujun

**Comment by xiaoyezao** [comment]
Hi Shujun,

In my case, the LTR sequence makes up about 40% of the genome, but only a few hundred intact LTRs are identified. I guess most of them are filtered out because of incompleteness. Some incomplete LTRs may have the complete 3' and 5' repeats. I am wondering is it possible to use these LTRs for insertion time estimation?

Thanks,

Tao

**Comment by oushujun** [comment]
Hi Tao,

You may, but you need to make sure the LTR is a single element but not combined from two LTR elements. In many cases, two LTR regions from two elements were picked up and reported as a single element. If you calculate the age based on this compound element, it will be misleading. Without complete structural info, it's hard to tell if the LTR candidate is a single element, that's why those were filtered out.

Best,
Shujun
