### ISSUE TITLE
LTR insertion time

### ISSUE THREAD

**Issue by liulu0827** [oushujun/LTR_retriever#82]
Hi, shujun,

I am trying using ltr_retriever to calculate LTR insertion time. Here is the command I used:
**LTR_retriever -genome $ASSEMBLY -inharvest $ASSEMBLY.harvest.scn -infinder $ASSEMBLY.finder.scn -threads 40**

However, according to the result of mod.pass.list, the burst of LTR occurred at ~0.2 Ma, it's weird (Fig. 1). As I know, the common burst of LTR is at  1-5 Ma. Especially, a close relative of my species is ~1.8 Ma. Is there any important parameters I should pay attention to? or do I misunderstand this result? I am really confused with this result.

<img width="415" alt="image" src="https://user-images.githubusercontent.com/56630007/92677808-324f8d00-f357-11ea-94fa-f0883b27d945.png">
Fig. 1

By the way, I also used EDTA. The result is similar in the file .mod.EDTA.raw/LTR/.mod.pass.list. Here is the command I used:
**./EDTA.pl -genome $ASSEMBLY -species others -step all -evaluate 1 -sensitive 1 -anno 1**

Best,

Lu Liu.

**Comment by oushujun** [comment]
Hi Lu,

First thing you may need to set the mutation rate of your species with `-miu` or at least using the same mutation rate for the two analyses to be comparable.

If you have done this, then pay attention to what LTR elements are used in the two analyses. In LTR_retriever, only intact LTR elements are used. If you include more fragmented or much-mutated elements, the peak may shift.

Then, please double check if the two analyses were based on the same genome. If not, please check the quality of both genomes because the LTR assembly is usually depleted in poorly assembled genomes. You may check out the LAI metric which was developed to evaluate the assembly quality of the TE space. Below is an example of how LTR age distribution could be shifted due to genome quality. Similarily, error polishing will affect the age distribution because sequencing errors are counted as mutations for age calculations.

![image](https://user-images.githubusercontent.com/5996084/92992494-f3354f00-f4b0-11ea-8668-149b9920391f.png)

Lastly, based on my experience, an intact LTR age peak on 0.2 MY is VERY common to a degree that if you don't see this peak, you should question the quality of your genome. Based on your description, your genome is not weird at all.

Best,
Shujun

**Comment by liulu0827** [comment]
Hi Shujun,

Thanks for your reply.

I checked all you mentioned, the mutation rate, intact LTR and the quality of genomes. The LAI score of my genome assembly is 18. The others you mentioned have no problems except of the LTR insertion of relative species. The LTR insertion of relative actually occured from 1.8 Mya, not has a peak on 1.8 Mya. And I analysed the genome of the relative, the result was similar with my species genome.

So I think it's a normal result of  0.2 Mya, just I don't see this peak before.

Thanks a lot,
Lu Liu

**Comment by amvarani** [comment]
Hi there, 
Sorry, I know that this is a closed topic, but I would like to ask which script you used to make these plots of the LTR insertion time ?

**Comment by oushujun** [comment]
Hi @amvarani,

You may try the ggplot2 package in R. I usually make geom_histogram or geom_density plots for LTR insertion time.

Best,
Shujun

**Comment by Jiangjiangzhang6** [comment]
hello,  shujun,
I draw the plot like this 
![image](https://github.com/oushujun/LTR_retriever/assets/101324838/b2fe8346-5009-4ac7-b372-ea59aaba28a0)
my LAI was 24,  gap-free , so its normal?

**Comment by oushujun** [comment]
@Jiangjiangzhang6, yup, looks like a typical plant genome in high quality and with abundant LTR activities in the scale of evolution time.

**Comment by Jiangjiangzhang6** [comment]
> Lastly, based on my experience, an intact LTR age peak on 0.2 MY is VERY common to a degree that if you don't see this peak, you should question the quality of your genome. Based on your description, your genome is not weird at all

sorry for that， its  a late answer, I saw the front the relationshio of  LAI and the ltr insertion time, the LAI higher and the peak of insertion time near zero. 
I just has the puzzled about that, if the situation was that, the ltr insertion time estimated was just with no meanning 
looking forward to your reply

**Comment by oushujun** [comment]
Just an update here, since v3.0.2, LTR_retriever allows user to specify three distance models, p-distance, K2P (default), and JC69: https://github.com/oushujun/LTR_retriever/releases/tag/v3.0.2

If you want to recompute the divergence of intact LTR-RTs, you can use this script we recently released:
https://github.com/cwb14/TESS/blob/main/PrinTE/bin/seq_divergence.py. Input is a fasta file with full-length LTR sequences; outputs are divergence estimates using the p-distance, JC69, and K2P models.

Cheers,
Shujun
