### ISSUE TITLE
how to use a TE library from different accession as input to extract TEs?

### ISSUE THREAD

**Issue by bioteksampath** [oushujun/LTR_retriever#9]
Hi
I found this tool is really interesting and I like to use it for my research.
I have a TE library generated from canola_A genotype in fasta and gff format and I like to use the same library to retrieve TE from Canola_B (different genotype) accession. 
how can I this canola_A TElibrary as input to extract the ****all** the TE members** ( expecting more copies in  Canola_B) from Canola_B.

I believe that your suggestions will be really helpful.

Thanks & regards
sam

**Comment by oushujun** [comment]
Hi Sam,

Thank you for using our method! If you think the canola A has a better
genome quality and the two genome has no difference in LTR family despite
different copy number, you can use the library on canola B. Otherwise it's
more recommended to scan LTR again on the B genome, and combine both fasta
libraries together for more a comprehensive annotation. You may use
RepeatMasker for whole-genome annotation with your custom library.

Let me know if you have more questions. Thanks!

Best,
Shujun


On Jan 18, 2018 11:52 AM, "bioteksampath" <notifications@github.com> wrote:

Hi
I found this tool is really interesting and I like to use it for my
research.
I have a TE library generated from canola_A genotype in fasta and gff
format and I like to use the same library to retrieve TE from Canola_B
(different genotype) accession.
how can I this canola_A TElibrary as input to extract the *all the TE
members* ( expecting more copies in Canola_B) from Canola_B.

I believe that your suggestions will be really helpful.

Thanks & regards
sam

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oushujun/LTR_retriever/issues/9>, or mute the thread

**Comment by bioteksampath** [comment]
Hi Shujun,
Thanks for your prompt reply.
Yes, I can use Repeatmasker to quantify the repeat proportion. But my aim is to retrieve the members of each family in redundant to see the difference between both genotypes.

so, how can I use LTRreteriver to extract members directly from fasta sequences AS INPUT but not with screen outputs of LTRfinder, LTRharvest or MGEScan.

Thanks
sam

**Comment by oushujun** [comment]
Hi Sam,

If I understand correctly, you want to extract sequences of all intact LTR
elements and compare them between genomes. It's possible, but not directly,
and may involve in some coding.

First you can use the pass.list file to get the coordinates of all intact
elements, then use the script bin/call_seq_by_list.pl to retrieve these
sequences from genome. Usage see -h or the manual. Then using the intact
sequence, you can do BLAST to locate intact elements in genome B. You may
need some filtering to get full length elements from the BLAST result.

Hope these help!

Best,
Shujun

On Jan 18, 2018 3:20 PM, "bioteksampath" <notifications@github.com> wrote:

Hi Shujun,
Thanks for your prompt reply.
Yes, I can use Repeatmasker to quantify the repeat proportion. But my aim
is to retrieve the members of each family in redundant to see the
difference between both genotypes.

so, how can I use LTRreteriver to extract members directly from fasta
sequences AS INPUT but not with screen outputs of LTRfinder, LTRharvest or
MGEScan.

Thanks
sam

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/oushujun/LTR_retriever/issues/9#issuecomment-358801031>,
or mute the thread

**Comment by bioteksampath** [comment]
Thanks again Shujun, I will try and get back to u if necessary!

**Comment by oushujun** [comment]
Good luck!

On Jan 18, 2018 3:52 PM, "Sam" <notifications@github.com> wrote:

Thanks again Shujun, I will try and get back to u if necessary!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/oushujun/LTR_retriever/issues/9#issuecomment-358808542>,
or mute the thread
